In [1]:
import numpy as np

In [2]:
a = np.linspace(-np.pi,np.pi,100)
b = np.cos(a)
c = np.sin(a)

In [3]:
b@c

-1.8041124150158794e-16

In [4]:
a

array([-3.14159265, -3.07812614, -3.01465962, -2.9511931 , -2.88772658,
       -2.82426006, -2.76079354, -2.69732703, -2.63386051, -2.57039399,
       -2.50692747, -2.44346095, -2.37999443, -2.31652792, -2.2530614 ,
       -2.18959488, -2.12612836, -2.06266184, -1.99919533, -1.93572881,
       -1.87226229, -1.80879577, -1.74532925, -1.68186273, -1.61839622,
       -1.5549297 , -1.49146318, -1.42799666, -1.36453014, -1.30106362,
       -1.23759711, -1.17413059, -1.11066407, -1.04719755, -0.98373103,
       -0.92026451, -0.856798  , -0.79333148, -0.72986496, -0.66639844,
       -0.60293192, -0.53946541, -0.47599889, -0.41253237, -0.34906585,
       -0.28559933, -0.22213281, -0.1586663 , -0.09519978, -0.03173326,
        0.03173326,  0.09519978,  0.1586663 ,  0.22213281,  0.28559933,
        0.34906585,  0.41253237,  0.47599889,  0.53946541,  0.60293192,
        0.66639844,  0.72986496,  0.79333148,  0.856798  ,  0.92026451,
        0.98373103,  1.04719755,  1.11066407,  1.17413059,  1.23

In [5]:
b

array([-1.        , -0.99798668, -0.99195481, -0.9819287 , -0.9679487 ,
       -0.95007112, -0.92836793, -0.90292654, -0.87384938, -0.84125353,
       -0.80527026, -0.76604444, -0.72373404, -0.67850941, -0.63055267,
       -0.58005691, -0.52722547, -0.47227107, -0.41541501, -0.35688622,
       -0.29692038, -0.23575894, -0.17364818, -0.1108382 , -0.04758192,
        0.01586596,  0.07924996,  0.14231484,  0.20480667,  0.26647381,
        0.32706796,  0.38634513,  0.44406661,  0.5       ,  0.55392006,
        0.60560969,  0.65486073,  0.70147489,  0.74526445,  0.78605309,
        0.82367658,  0.85798341,  0.88883545,  0.91610846,  0.93969262,
        0.95949297,  0.97542979,  0.98743889,  0.99547192,  0.99949654,
        0.99949654,  0.99547192,  0.98743889,  0.97542979,  0.95949297,
        0.93969262,  0.91610846,  0.88883545,  0.85798341,  0.82367658,
        0.78605309,  0.74526445,  0.70147489,  0.65486073,  0.60560969,
        0.55392006,  0.5       ,  0.44406661,  0.38634513,  0.32

In [6]:
c

array([-1.22464680e-16, -6.34239197e-02, -1.26592454e-01, -1.89251244e-01,
       -2.51147987e-01, -3.12033446e-01, -3.71662456e-01, -4.29794912e-01,
       -4.86196736e-01, -5.40640817e-01, -5.92907929e-01, -6.42787610e-01,
       -6.90079011e-01, -7.34591709e-01, -7.76146464e-01, -8.14575952e-01,
       -8.49725430e-01, -8.81453363e-01, -9.09631995e-01, -9.34147860e-01,
       -9.54902241e-01, -9.71811568e-01, -9.84807753e-01, -9.93838464e-01,
       -9.98867339e-01, -9.99874128e-01, -9.96854776e-01, -9.89821442e-01,
       -9.78802446e-01, -9.63842159e-01, -9.45000819e-01, -9.22354294e-01,
       -8.95993774e-01, -8.66025404e-01, -8.32569855e-01, -7.95761841e-01,
       -7.55749574e-01, -7.12694171e-01, -6.66769001e-01, -6.18158986e-01,
       -5.67059864e-01, -5.13677392e-01, -4.58226522e-01, -4.00930535e-01,
       -3.42020143e-01, -2.81732557e-01, -2.20310533e-01, -1.58001396e-01,
       -9.50560433e-02, -3.17279335e-02,  3.17279335e-02,  9.50560433e-02,
        1.58001396e-01,  

In [7]:
(b@c).round(2)

-0.0

In [8]:
from scipy.stats import norm
from scipy.integrate import quad

In [9]:
ϕ = norm()

In [10]:
value, error = quad(ϕ.pdf, -2,2)

In [11]:
value

0.9544997361036417

In [12]:
error

1.8403548653972355e-11

In [13]:
-3

-3

In [14]:
from sympy import symbols

In [15]:
x, y = symbols ('x,y')

In [16]:
x+x+x+y

3*x + y

In [17]:
import sympy

In [ ]:
sympy.

In [18]:
from sympy import *

In [19]:
expression = (x + y)**2

In [20]:
expression.expand()

x**2 + 2*x*y + y**2

In [21]:
solve (x**2 + x + 2)

[-1/2 - sqrt(7)*I/2, -1/2 + sqrt(7)*I/2]

In [22]:
diff (sin(x), x)

cos(x)

In [23]:
diff (tan(x), x)

tan(x)**2 + 1

In [24]:
import pandas as pd
np.random.seed(1234)

In [25]:
data = np.random.randn (5, 2)

In [26]:
data 

array([[ 0.47143516, -1.19097569],
       [ 1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495]])

In [27]:
dates = pd.date_range ('28/ 12/2010', periods = 5)

In [28]:
dates

DatetimeIndex(['2010-12-28', '2010-12-29', '2010-12-30', '2010-12-31',
               '2011-01-01'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df = pd.DataFrame (data, columns = ('price', 'weight'), index = dates)

In [30]:
print (df)

               price    weight
2010-12-28  0.471435 -1.190976
2010-12-29  1.432707 -0.312652
2010-12-30 -0.720589  0.887163
2010-12-31  0.859588 -0.636524
2011-01-01  0.015696 -2.242685


In [31]:
df.mean ()

price     0.411768
weight   -0.699135
dtype: float64

In [7]:

    import numpy as np
    def quadratic_equation (a, b, c)
    def

SyntaxError: invalid syntax (3185976269.py, line 2)

In [2]:
import cmath

def quadratic_equation(a, b, c):
    root = cmath.sqrt(b**2 - 4*a*c)
    x1 = (-b + root) / (2*a)
    x2 = (-b - root) / (2*a)
    return x1, x2




In [3]:
print(quadratic_equation(1, -3, 2))

((2+0j), (1+0j))


In [5]:
from sympy import symbols , solve

def quadratic_equation(a,b,c):
    x = symbols ('x')
    return solve (a*x**2 + b*c + c , x )
    
    

In [6]:
print(quadratic_equation(1, -3, 2))

[-2, 2]


In [1]:
def FutureValue(PV, rate, time): #FV =PV(1+r)**2
    result = PV*(1+rate)**time
    return result 

In [2]:
FV = FutureValue(5000, 0.21, 4)

In [3]:
FV

10717.944049999998

In [4]:
import this #string is the combination of characters

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [5]:
print?

In [6]:
name = 'Berlinda Atuahene'

In [7]:
name

'Berlinda Atuahene'

In [8]:
name.count

<function str.count>

In [10]:
name.count ()

TypeError: count() takes at least 1 argument (0 given)

In [11]:
name.capitalize 

<function str.capitalize()>

In [12]:
name.capitalize()

'Berlinda atuahene'

In [13]:
type(name)

str

In [14]:
3

3

In [17]:
type (3)

int

In [18]:
type('50')

str

In [19]:
a = '5'
b = '15'

In [20]:
a * b

TypeError: can't multiply sequence by non-int of type 'str'

In [21]:
3 * a

'555'

In [22]:
name.upper()

'BERLINDA ATUAHENE'

In [23]:
name.capitalize()

'Berlinda atuahene'

In [24]:
name.lower() #codes must always have whitespace for readability 
# use backslash for page break \

'berlinda atuahene'

In [25]:
print ('Hello\tworld')

Hello	world


In [26]:
print ('Hello\bWorld')

HelloWorld


In [27]:
#python has two numbers stored,integers and floats

In [31]:
import numpy as np #distingusish between stored numbers ie integers and float

In [32]:
np .pi

3.141592653589793

In [33]:
xi = 1; xf = 1.0

In [34]:
xi

1

In [35]:
xf

1.0

In [36]:
zf = 1_230.5


In [38]:
zf

1230.5

2 * 1.0

In [39]:
2 * 1.0

2.0

In [40]:
2 * 1

2

In [41]:
10 / 2 #in division answers can be  in float

5.0

In [43]:
10 // 2 # double // restricts outputs to integers

5

In [44]:
import math 

In [45]:
math.sin(2.5)

0.5984721441039564

In [49]:
math.cos(np.pi/2)

6.123233995736766e-17

In [50]:
(math.cos(np.pi/2)).round(2)

AttributeError: 'float' object has no attribute 'round'

In [53]:
math.cos(np.pi/2)

6.123233995736766e-17

In [54]:
np.cos(2.5)

-0.8011436155469337

In [55]:
(np.cos(2.5)).round(2)

-0.8

In [56]:
(np.cos(np.pi/2)).round(2)

0.0

In [57]:
7 // 2

3

In [58]:
7 % 2

1

In [59]:
this is not a string

SyntaxError: invalid syntax (707683720.py, line 1)

In [60]:
'this is a string'

'this is a string'

In [61]:
type('this is a string')

str

In [62]:
'Jame's Class' # take notes of quotes inside words

SyntaxError: invalid syntax (2553443880.py, line 1)

In [63]:
"James's Class"

"James's Class"

In [68]:
'James's\Class'

SyntaxError: invalid syntax (754657583.py, line 1)

In [69]:
# WE CREATE LISTS WITH SQUARE BRACKETS 

In [70]:
[1, 3, 7]

[1, 3, 7]

In [73]:
various_things = [1, 2, 'banana', 3.4, [1, 2]] # python starts counting from zero

In [74]:
various_things[2]

'banana'

In [75]:
index = 0
various_things[index]

1

In [76]:
"Dog" in ["Cat","Dog", "Horse"]

True

In [77]:
"Bird" in ["Cat","Dog", "Horse"]

False

In [78]:
range (5)

range(0, 5)

In [79]:
list (range (5)) #range is always n-1

[0, 1, 2, 3, 4]

In [80]:
various_things[3] = 3.46

In [81]:
various_things #lists are said to be mutable ie they are assigned to change

[1, 2, 'banana', 3.46, [1, 2]]

In [82]:
my_tuple = ("Hello", "World")

In [83]:
my_tuple[0] ="Goodbye" #tuples are immutable, they are not up for change

TypeError: 'tuple' object does not support item assignment

In [84]:
fish = "Hake"

In [85]:
fish [0] = "R"  #strings does not allow change #dictionary is made upof key value words {}

TypeError: 'str' object does not support item assignment

In [86]:
CourseGrade = {'DMA803':'A', 'FIN401':'B', 'MATH900':'A', 'FUN101':'A'}

In [107]:
CourseGrade.keys ()

AttributeError: 'set' object has no attribute 'keys'

In [ ]:
 I am learning python